- dts/arm/alif/balletto_fpga_rtss_common.dtsi
- dts/arm/alif/balletto_rtss_common.dtsi
Fixed some compile warnings from Balletto FPGA.
Cherry-picked from dev repository
> Balletto fpga warning fix

- soc/arm/alif_balletto/b1/soc_b1_dk_rtss_he.c
Added ES0 shuttdown before call SoC reset.
> soc: alif_balletto: b1: Reboot fix

- modules/hal_ethos_u/CMakeLists.txt
Added cache attribute for NPU config and log severity
> cmake: ethos: Corrected Ethos parameters

- MAINTAINERS.yml
- boards/arm/alif_b1_dk/Kconfig.defconfig
- drivers/adc/Kconfig.alif
- drivers/can/Kconfig.cast
- drivers/comparator/Kconfig.alif
- drivers/crc/Kconfig.alif
- drivers/i2c/Kconfig.alif
- drivers/spi/Kconfig.dw
- modules/Kconfig.alif
This will fix boolean and prompt errors from compliance check
> Fix some of the compliance errors

- drivers/ieee802154/Kconfig.alif
- drivers/ieee802154/ieee802154_alif.c
- drivers/ieee802154/ieee802154_alif.h
- modules/openthread/platform/alarm.c
- west.yml
Added support for B1 ROM v122 15.4 support.
Depends on https://github.com/alifsemi/hal_alif/pull/3
> Balletto ROM 15.4  v122 update

- west.yml
Ethos cache handling callbacks implementations.
> manifest: Updates HAL Alif

- soc/arm/alif_balletto/common/Kconfig.soc
- soc/arm/alif_ensemble/common/Kconfig.soc
Fixed variable in Kconfig for alif SoC
> soc: alif: Fix SPI driver enable warning

- west.yml
Manifest update for https://github.com/alifsemi/hal_alif/pull/12
> mainifest: HAL Alif updated

- drivers/ieee802154/ieee802154_alif.c
- west.yml
Update hal alif manifest.
Fixed ieee802.15.4 IE vendor data write
SE service TOC version read update
ES0 power manager use synch for boot and check TOC version number for es0 shuttdown needs.
> manifest: Update HAL alif

- drivers/dma/dma_pl330.c
- drivers/dma/dma_pl330.h
Added support for simultaneously operating DMA instances on the Alif Ensemble family.
> drivers: dma: add support for multiple instances.

- boards/arm/alif_b1_dk/alif_b1_dk_rtss_he.dts
- boards/arm/alif_e1c_dk/alif_e1c_dk_rtss_he.dts
- boards/arm/alif_e7_dk/alif_e7_dk_rtss_he.dts
- boards/arm/alif_e7_dk/alif_e7_dk_rtss_hp.dts
Added a memory region for external flash.
> boards: arm: alif_e7_dk alif_b1_dk alif_e1c_dk: OSPI XIP memory region

- dts/arm/alif/ensemble-e1c-pinctrl.dtsi
- dts/arm/alif/ensemble_e1c_rtss.dtsi
Updated E1C OSPI pinmux default to latest DevKit revision
> dts: arm: alif: Updated e1c pinmux config

- drivers/ieee802154/ieee802154_alif.c
- drivers/ieee802154/ieee802154_alif.h
- dts/arm/alif/balletto_rtss_common.dtsi
- west.yml
Fixed compile warnings for ethos and SE region
Fixed 802.15.4 drivent event handler.
Updated HAL manifest
> Balletto platform update

- drivers/flash/flash_ospi_is25wx.c
- dts/bindings/ospi/snps,designware-ospi.yaml
- west.yml
Depends on alifsemi/hal_alif#26.
> Enable the baud2 delay automatically by default

- automation/Jenkinsfile
removed docker build and setup initial build steps.
> build: automation: jenkins file update

- drivers/i2c/i2c_dw.c
- drivers/i2c/i2c_dw.h
included clock controller module to drive input clock
> drivers: i2c: add clock control support

- automation/Jenkinsfile
checkout mechanism has been update.
> build: automation: correction in jenkins automation

- drivers/comparator/alif_cmp.c
- dts/arm/alif/ensemble-pinctrl.dtsi
Driver code modification required for the lpcmp.
> drivers: comparator: Modified analog comparator driver

- boards/arm/alif_b1_dk/alif_b1_dk_rtss_he.dts
- boards/arm/alif_e1c_dk/alif_e1c_dk_rtss_he.dts
Add mcumgr UARTS to the device tree.
> boards: arm: alif_e1c/b1_dk : Add mcumgr UARTS

- automation/Jenkinsfile
validation of commit message of pull request i.e. PR commit message validation support is added
> automation: jenkins: validate commit message of raised pull request

- drivers/flash/flash_mram_alif.c
Added support for mram write unaligned data.
Moved "write_16bytes" and "erase_16bytes" apis from HAL to flash_mram_alif.c.
in future releases above apis will be removed from HAL repo.
> drivers: flash: mram: add support for write unaligned data

- samples/drivers/counter/alarm/boards/alif_lptimer.overlay
- samples/drivers/counter/alarm/boards/alif_rtc.overlay
Corrected LPTIMER and RTC overlay files used in the alarm app.
> samples: correct overlays for LPTIMER and RTC alarm app

- automation/Jenkinsfile
gitlint and PR checks will run for all pushed commits.
> automation: jenkins: PR checks runs for all commits

- automation/Jenkinsfile
skipping first commit in case of git rebase.
> automation: jenkins: ignore git rebase commmit

- automation/Jenkinsfile
added a check to skip PR and gitlint operations when no commit found.
> automation: jenkins: skip PR and gitlint checks in-case no commit found

- drivers/dma/dma_pl330.c
- drivers/dma/dma_pl330.h
- drivers/serial/Kconfig.ns16550
- drivers/serial/uart_ns16550.c
Add support for PL330 DMA to ns16550 UART driver driver to get async UART working properly.
> drivers: ns16550: Async UART support for PL330 DMA

- west.yml
West.yml updated to get hal_alif changes in.
See: https://github.com/alifsemi/hal_alif/pull/33
> Added configs for sleep clock and active clock drifts

- west.yml
> manifest: Fix NVDS length calculation

- automation/Jenkinsfile
jenkin build support for zephyr 4.x
> automation: jenkins: initial jenkin script added

- west.yml
> manifest: Fix non alif board build

- west.yml
Update manifest file to point to
https://github.com/alifsemi/hal_alif/pull/38
> west.yml: update manifest file

- west.yml
License change.
Depends on alifsemi/hal_alif#41.
> manifest: update hal_alif

- soc/arm/alif_ensemble/e3/soc_e3_dk_rtss_he.c
- soc/arm/alif_ensemble/e3/soc_e3_dk_rtss_hp.c
- soc/arm/alif_ensemble/e7/soc_e7_dk_rtss_he.c
- soc/arm/alif_ensemble/e7/soc_e7_dk_rtss_hp.c
Removed unused HOSTUARTCLK configuration.
> soc: arm: alif: ensemble: Remove unused HOSTUARTCLK

- drivers/spi/spi_dw.c
Added fix for Slv Select Toggle configuration.
from https://github.com/alifsemi/zephyr_alif_1.4/commit/f8b87145e25368aa0bb0c52a3907844f5c8f2e43.
> drivers: dw_spi: fix Slv Select Toggle

- west.yml
Update hal_alif revisison to Include patch library and sources if patch file exists.
Depends on: https://github.com/alifsemi/hal_alif/pull/47
> manifest: update hal_alif to Include patch if patch file exists.

- scripts/west_commands/runners/alif_flash.py
[fix] alif_flash was not working when the build target was in subfolder
alif_flash runner was broken when a build-dir was set:
```
./build/alif_e7_dk_rtss_he/blinky
```
```
west flash --runner alif_flash --build-dir ./build/alif_e7_dk_rtss_he/blinky
```
that was caused by the too early cd and by the hardwired location of the zephyr.bin
also restoring the directory was missing after the ToC was done/failed
> [fix] alif_flash was not working when the build target was in subfolder

- west.yml
Take a AHI uart fix.
Dependson https://github.com/alifsemi/hal_alif/pull/52
> manifest: Hal alif update

- west.yml
> manifest: Update HAL repo.
