alifsemi/zephyr_alif

dts/arm/alif/balletto_rtss_common.dtsi
dts/arm/alif/ensemble_e1c_rtss.dtsi

Mt9m114 is removed as B1 and E1C DKs does not have it.

Removed mt9m114 from soc in E1C & B1

---

drivers/video/video_alif.c
dts/arm/alif/ensemble_rtss_common.dtsi

- Mt9m114 and arx3a0 camera sensor nodes are removed from soc devicetree since e7 ensemble does not have it.
- Removed dead code from soc devicetree for display and video nodes.
- Moved fourcc_to_csi_data_type() API definition under if CONFIG_VIDEO_MIPI_CSI2_DW condition check to avoid unnecessary inclusion of the API definition for LPCAM app compilation and generated warning of unused function.

drivers: video: alif: Removed camera sensors from soc dts for Ensemble E7 board

---

dts/arm/alif/balletto_rtss_common.dtsi

Adding a reserved area for SE at the end of MRAM.

dts: arm: alif: MRAM partition for SE.

---

drivers/serial/uart_ns16550.c

If DLF is defined, divisor must not be rounded up.

drivers: serial: Fix uart baud rate divisor calculation

---

dts/arm/alif/ensemble_rtss_common.dtsi

Moved the reference to the CSI bus node in the camera controller node from the SoC DTS to the ARX3A0 camera sensor overlay, as we need a reference to this bus only in the case of serial camera sensors.

dts: arm: alif: ensemble: Remove reference to CSI bus node

---

drivers/bluetooth/hci/hci_alif.c
drivers/counter/counter_dw_rtc.c
drivers/serial/uart_ns16550.c
soc/arm/alif_balletto/b1/soc_b1_dk_rtss_he.c
soc/arm/alif_balletto/b1/soc_b1_fpga_rtss_he.c
west.yml

* Updates the ns16550 UART driver to support using the line as a Wakeup source.
* BLE HCI & 802154 AHI support for the wakeup
Depends on alifsemi/hal_alif#7.

drivers: uart: ns16550: Wakeup support

---

dts/bindings/vendor-prefixes.txt

Added 'focuslcd' as a new vendor prefix in the vendor-prefixes.txt file to include Focus LCD as a recognized vendor for device tree bindings.

dts: bindings: Add 'focuslcd' to vendor-prefixes.txt

---

dts/bindings/vendor-prefixes.txt

Added 'tes' as a new vendor prefix in the vendor-prefixes.txt file to include Tes CDC as a recognized vendor for device tree bindings.

dts: bindings: Add 'tes' to vendor-prefixes.txt

---

soc/arm/alif_balletto/b1/soc_b1_dk_rtss_he.c
west.yml

Makes possible to use Zephyr's Bluetooth stack with Ensemble targets.
Depends on alifsemi/hal_alif#9.

manifest: update HAL

---

boards/arm/alif_b1_dk/alif_b1_fpga_rtss_he_ble_defconfig

Add ROM version 1.2 support for FPGA target.

boards: arm: alif_b1_dk: ROM v1.2 support for FPGA target.

---

dts/bindings/vendor-prefixes.txt

Updated the vendor name to 'Focus LCDs' in the vendor-prefixes.txt file.

dts: bindings: Update vendor name to Focus LCDs

---

drivers/flash/flash_ospi_is25wx.c

ARM-GCC compiler treating off_t as long int type and Arm-clang treat this is uint32_t.
As per Zephyr it should be treated as integer pointer.
Zephyr [off_t reference](https://docs.zephyrproject.org/latest/doxygen/html/lib_2libc_2minimal_2include_2sys_2types_8h.html#a98a5cc5f4a350bf5652565021a2f239f)

drv: ospi-flash: removed warnings

---

drivers/display/Kconfig.cdc200

Removed the pointless menuconfig without children from kconfig for CDC200 driver.

drivers: cdc200: remove pointless menuconfig

---

west.yml

Update hal alif manifest for BLE v125
Depends on: https://github.com/alifsemi/hal_alif/pull/15

manifest: Update HAL Alif

---

soc/arm/alif_ensemble/Kconfig

Added support for SEGGER RTT in the Ensemble SoC.

soc: arm: ensemble: Kconfig: Add SEGGER RTT support

---

drivers/gpio/gpio_dw.c

Changed DT_INST_IRQ to DT_INST_IRQ_BY_IDX to correctly index IRQ priority, which was always pointing to 0th index of the device tree.
https://alifsemi.atlassian.net/browse/ZRTSS-480

drivers: gpio_dw: Fix IRQ Priority Device Tree Property Indexing

---

soc/arm/alif_balletto/CMakeLists.txt
soc/arm/alif_balletto/common/Kconfig.soc
soc/arm/alif_balletto/common/alif_ospi.ld
soc/arm/alif_ensemble/CMakeLists.txt
soc/arm/alif_ensemble/common/Kconfig.soc
soc/arm/alif_ensemble/common/alif_ospi.ld

Added OSPI[0|1] linker sections.
Added generation of separate .bin files for external flash and MRAM.

soc: arm: alif_ensemble alif_balletto: OSPI XIP memory region handling

---

boards/arm/alif_e3_dk/alif_e3_dk_rtss_he.dts
boards/arm/alif_e3_dk/alif_e3_dk_rtss_hp.dts
boards/arm/alif_e7_dk/alif_e7_dk_rtss_he.dts
boards/arm/alif_e7_dk/alif_e7_dk_rtss_hp.dts
dts/arm/alif/balletto_fpga_rtss_common.dtsi
dts/arm/alif/balletto_rtss_common.dtsi
dts/arm/alif/ensemble_e1c_rtss.dtsi
dts/arm/alif/ensemble_rtss_common.dtsi

- Set NVIC num-irq-priority-bits to 8 for both Ensemble and Balletto families.
- For Ensemble, relocated irq-priority-bits from board files to DTS.
- Updated default IRQ priority level to 0 (to match with CMSIS pack).
https://alifsemi.atlassian.net/browse/ZRTSS-480

dts: arm: alif: Ensemble/Balletto: Update NVIC IRQ priority bits to 8

---

drivers/ipm/ipm_arm_mhuv2.c
drivers/ipm/ipm_arm_mhuv2.h
include/zephyr/drivers/ipm.h
west.yml

1. polling mode feature is added.
2. mhu driver init level is changed to PRE_KERNEL_1 to initialize before systop peripherals.
3. depends on: https://github.com/alifsemi/hal_alif/pull/17

drivers: ipm: ipm_arm_mhuv2: add polling mode support in driver

---

dts/arm/alif/balletto_rtss_common.dtsi
dts/arm/alif/ensemble_e1c_rtss.dtsi

Fix for using low OSPI baudrates.

dts: arm: alif: E1C and B1 OSPI wait cycle fix

---

boards/arm/alif_e3_dk/alif_e3_dk_rtss_he.dts
boards/arm/alif_e3_dk/alif_e3_dk_rtss_hp.dts
boards/arm/alif_e7_dk/alif_e7_dk_rtss_he.dts
boards/arm/alif_e7_dk/alif_e7_dk_rtss_hp.dts
dts/arm/alif/ensemble_rtss_he.dtsi
dts/arm/alif/ensemble_rtss_hp.dtsi

Add` zephyr,uart-mcumgr` chosen nodes for the ensemble e3/e7 devkits. Increase the application image slot sizes for mcuboot compatible application builds. Also, move the mram storage partitions from the board device tree files into the HP/HE core device tree include files as that is where they really belong. While increasing the image slot sizes, care has been taken to not to overflow into the mcuboot/non-mcuboot application builds for the other core (The current `FLASH_LOAD_OFFSET` for HP is at 2MB).

Fixes for mcuboot/mcumgr 

---

drivers/i2c/Kconfig.dw
drivers/i2c/i2c_dw.c

Solves two identical issues listed below:
Issue 1: I2C scanner example for DesignWare hardware gets stuck indefenitely resulting in system hang up.This is because DW I2C driver does not handle 0 byte transfer correctly which is the case for I2C scan example.
Fixed it by overwriting the msg length to 1 if it is 0 and the buffer is not NULL.
Issue 2: Similarly, if the I2C pins are not pulled up (nothing connected
to I2C pins), the DW hardware does not actually send the data
(assuming contention on the bus) hence not releasing the semaphore resulting in calling thread waiting forever.
Fixed it by adding a timeout to k_sem_take call and return error if cannot successfully acquire it.
Tested scenarios where nothing was connected on the bus and saw the I2C scan example complete the whole scan …

drivers: I2C_DW: Fix I2C scan example

---

west.yml

Fixes BLE UTIMER dependecy.
https://github.com/alifsemi/hal_alif/pull/27 must be merged before this!

manifest: HAL Alif updated

---

drivers/flash/flash_ospi_is25wx.c
drivers/flash/flash_ospi_is25wx.h
dts/arm/alif/balletto_rtss_common.dtsi
dts/arm/alif/ensemble_e1c_rtss.dtsi
dts/arm/alif/ensemble_rtss_common.dtsi
dts/bindings/ospi/snps,designware-ospi.yaml
samples/drivers/flash_shell/boards/alif_b1_dk_rtss_he.overlay
samples/drivers/flash_shell/boards/alif_e1c_dk_rtss_he.overlay
samples/drivers/flash_shell/boards/alif_e3_dk_rtss_he.overlay
samples/drivers/flash_shell/boards/alif_e3_dk_rtss_hp.overlay
samples/drivers/flash_shell/boards/alif_e7_dk_rtss_he.overlay
samples/drivers/flash_shell/boards/alif_e7_dk_rtss_hp.overlay

**_### OSPI Input Clk configuration._**
* Updated ospi clk frequency from hardcoded.
* Clock Frequency shall be retrieved from OSPI node
**_### Supporting Flash access through Shell module._**
+ Added 8-bit buffer R/W changes as required for shell module to read and write the content to Flash.
+ Renamed to Flash controller node. OSPI driver not exposed from Zephyr and it implemented through HAL.
+ Flash properties updated and Storage node added.
+ Renamed macros to be generic.
#85 #67 : Combined in this PR.

ZRTSS Flash Shell support

---

dts/arm/alif/ensemble_rtss_common.dtsi

By default, all GPIOs are enabled, and during the pre-kernel stage, the GPIO driver sets all pinmux configurations to default (GPIO). This causes issues when multiple cores are running. For example, if the first core runs I2C and the second core runs SPI, the following sequence occurs:
- The first core sets the pinmux to I2C.
- The second core starts and sets all pins to their default (GPIO). This results in the pinmux configuration set by the first core being overwritten by the second core, breaking the first core's I2C functionality, while the second core works properly. To fix this issue, the default GPIO pinctrl property is removed.

dts: arm: Remove pinctrl from GPIOs in Ensemble

---

drivers/i2c/i2c_dw.c
drivers/i2c/i2c_dw.h
drivers/i2c/target/Kconfig
dts/arm/alif/balletto_rtss_common.dtsi
dts/arm/alif/ensemble_e1c_rtss.dtsi
dts/arm/alif/ensemble_rtss_common.dtsi
dts/bindings/i2c/i2c-controller.yaml

Configurable FIFO Thresholds:
- Added support for configurable TX and RX FIFO threshold values via Devicetree.
- Default Rx thresholds are set to 0 to ensure compatibility with both Stop and Restart transfer features.
Restart Mode Behavior:
- When Restart is used and data size is less than the configured threshold, the driver may break.
- Users should configure thresholds accordingly in the Devicetree (e.g., 4 for 4 or multiples of 4 bytes).
Target Slave Buffer Mode:
- Introduced support for buffer mode read and write callback functions.
Note: Buffer mode is not compatible with Restart, as no STOP is generated between write and read phases.
The following PR https://github.com/alifsemi/sdk-alif/pull/59 in i2c sample making use of the changes.

drivers: i2c: add buffer mode callback function support

---

west.yml

Update manifest for hal_alif ble address generation fix.
Depends on [hal_alif PR31](https://github.com/alifsemi/hal_alif/pull/31)

manifest_update

---

drivers/i2c/i2c_dw.c

Fixed the unused variable 'rx_fifo_level' warning when I2C_TARGET is not configured.

drivers: i2c: fix unused variable warning

---

drivers/i2s/alif_i2s_clk_config.h
samples/drivers/i2s/echo/boards/alif_e7_dk_rtss_he.overlay

Switched the I2S TX instance from I2S1 to I2S4 for the E7 RTSS HE core to demonstrate usage of the low-power I2S variant.
Removed unused STATIC_INLINE macro.

I2S changes

---

dts/arm/alif/ensemble-pinctrl.dtsi

Modified UTIMER1 pin pad settings to enable read functionality.

dts: ensemble: update UTIMER1 pin pad config

---

dts/arm/alif/balletto_fpga_rtss_common.dtsi

Build for FPGA was broken when utimers were modified. This commit updates balletto_fpga_rtss_common.dtsi file to fix build errors for alif_b1_fpga_rtss_he_ble target.

dts: arm: alif: fix fpga common dtsi

---

drivers/spi/spi_dw.c
drivers/spi/spi_dw.h
dts/arm/alif/balletto_rtss_common.dtsi
dts/arm/alif/ensemble_rtss_common.dtsi
dts/bindings/spi/snps,designware-spi.yaml

Support added for
-   Rx Delay configuration.
-   Enable or Disable Slave Select Toggling.

drivers : spi : spi_dw: SPI RX delay support

---

drivers/dma/dma_pl330.c
drivers/dma/dma_pl330.h
drivers/serial/uart_ns16550.c

Mutex is replaced by the atomic to be able to use PL330 DMA with the I2S.
UART init level is changed to KERNEL_POST by default and PRE_KERNEL_1 is used only for console uart. This allows DMA to be enabled for other UARTs.
Corresponding ALIF-SDK PR https://github.com/alifsemi/sdk-alif/pull/90.

driver, pl330: mutex removed and UART init level adjustment based on DMA configuration

---

drivers/ipm/ipm_arm_mhuv2.c
drivers/ipm/ipm_arm_mhuv2.h
west.yml

1. Updated the callback parameters as per zephyr standard.
2. user_data is any private data provided by app during initialization. It should be unmodified. So use last parameter to handle actual data.
This PR is dependent on https://github.com/alifsemi/hal_alif/pull/32
It has a dependent PR: https://github.com/alifsemi/sdk-alif/pull/116

drivers: ipm: mhuv2: update user callback params

---

drivers/bluetooth/hci/hci_alif.c

Fixed Driver init priority to CONFIG_APPLICATION_INIT_PRIORITY for guarantee that uart device driver is initialized.
Manifest update SDK: https://github.com/alifsemi/sdk-alif/pull/143

drivers: bluetooth: Alif HCI driver update

---

include/zephyr/toolchain/gcc.h
west.yml

With Clang you can't set long_call attribute on function basis. Instead
of converting all calls to long calls let the linker create veneers when
necessary.
Depends on PR alifsemi/hal_alif#34.
Upstream PR: zephyrproject-rtos/zephyr#90148

toolchain: gcc: fixes __ramfunc usage with Clang

---

boards/arm/alif_b1_dk/board.cmake
boards/arm/alif_e1c_dk/board.cmake
boards/arm/alif_e3_dk/board.cmake
boards/arm/alif_e7_dk/board.cmake
boards/common/alif_flash.board.cmake
scripts/west_commands/runners/__init__.py
scripts/west_commands/runners/alif_flash.py

West tool Flash support for writing binary into MRAM with Alif SE-Tools.
Based on build configuration JSON file prepared from existing cup stub configuration and ToC File generated. 
Generated ToC file will be written to MRAM.
Added support for Balletto and Ensemble.

scripts: west_commands: alif custom runner for flash

---

drivers/pwm/pwm_alif_utimer.c

Added support disbale PWM also when pulse is 0. Earlier only period 0 was disabling PWM pulse and set GPIO idle state. pwm_set_pulse_dt() API use device configured Period so it is never 0 but pulse is.

drivers: pwm: Alif pwm driver fix

---

dts/arm/alif/ensemble_rtss_common.dtsi

set SPI SS(slave select) default as H/W controlled. (for all the SPI modules SS pinmux is default set as H/W controlled,
user can refer samples/overlay files for S/W controlled(using gpio))

dts: arm: alif: ensemble: set SPI SS default as H/W controlled

---

west.yml

Balletto support DMA event router for HCI uart.
Depends on alifsemi/hal_alif#48.

Manifest update for HCI driver

---

west.yml

Update hal_alif revision to pick up se_services fixes to increase the SYNC timeout and improve semaphore usage.
Depends on: https://github.com/alifsemi/hal_alif/pull/49

manifest: update hal_alif revision to pick up se_service fixes

---

boards/arm/alif_b1_dk/alif_b1_dk_rtss_he.dts
boards/arm/alif_e1c_dk/alif_e1c_dk_rtss_he.dts
boards/arm/alif_e7_dk/alif_e7_dk_rtss_he.dts
boards/arm/alif_e7_dk/alif_e7_dk_rtss_hp.dts
dts/arm/alif/balletto_rtss_common.dtsi
dts/arm/alif/ensemble_e1c_rtss.dtsi
dts/arm/alif/ensemble_rtss_common.dtsi
samples/basic/blinky_pwm/boards/alif_b1_dk_rtss_he.overlay
samples/basic/blinky_pwm/boards/alif_e1c_dk_rtss_he.overlay
samples/basic/blinky_pwm/boards/alif_e7_dk_rtss_he.overlay
samples/basic/blinky_pwm/boards/alif_e7_dk_rtss_hp.overlay
samples/basic/fade_led/boards/alif_b1_dk_rtss_he.overlay
samples/basic/fade_led/boards/alif_e1c_dk_rtss_he.overlay
samples/basic/fade_led/boards/alif_e7_dk_rtss_he.overlay
samples/basic/fade_led/boards/alif_e7_dk_rtss_hp.overlay

* Moved led-pwm configurations from respective boards dts file to overlay files.
* Fixed node labels.

boards: arm: move led-pwm config from board dts to overlays

---

drivers/flash/Kconfig.alif

Update the flash Kconfig to remove the default selection of the ISSI flash driver.

drivers: flash: Do not enable ISSI flash driver by default

---

west.yml

Update hal_alif revision in manifest to point to
alif_ble_disable function implementation.
Depends on: https://github.com/alifsemi/hal_alif/pull/58

manifest: Update hal_alif to alif_ble_disable implementation.
